# Generated by Django 5.2 on 2025-04-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
