# Generated by Django 5.2 on 2025-04-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
