# Generated by Django 5.2 on 2025-04-09 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title text for the banner.', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or supporting text.', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Upload a banner image (JPG, PNG, WEBP).', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('enquiry_button_text', models.CharField(default='Enquire Now', help_text='Text shown on the enquiry button.', max_length=100)),
                ('enquiry_button_link', models.URLField(help_text='URL the enquiry button should link to.')),
            ],
        ),
    ]
