# Generated by Django 5.2 on 2025-04-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='total_views',
        ),
    ]
